@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Jan 13 20:55:39 -0600 2025
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab --debug typical --relax --mt 2 -d "DEBUG=1" -L xil_defaultlib -L axi_lite_ipif_v3_0_4 -L lib_pkg_v1_0_3 -L lib_srl_fifo_v1_0_3 -L lib_cdc_v1_0_2 -L axi_uartlite_v2_0_33 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot SimCPU_behav xil_defaultlib.SimCPU xil_defaultlib.glbl -log elaborate.log"
call xelab  --debug typical --relax --mt 2 -d "DEBUG=1" -L xil_defaultlib -L axi_lite_ipif_v3_0_4 -L lib_pkg_v1_0_3 -L lib_srl_fifo_v1_0_3 -L lib_cdc_v1_0_2 -L axi_uartlite_v2_0_33 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot SimCPU_behav xil_defaultlib.SimCPU xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
