standard = "2008"
[libraries]

xil_defaultlib.files = [
"CPU2.srcs\\sources_1\\cpu\\WaitTimer.vhd",
"CPU2.srcs\\sources_1\\cpu\\Utilities.vhdl",
"CPU2.srcs\\sources_1\\cpu\\Utilities_Body.vhdl",
"CPU2.srcs\\sources_1\\computer\\UartDevice.vhd",
"CPU2.srcs\\sources_1\\computer\\uart2wbm.vhd",
"CPU2.srcs\\sources_1\\cpu\\ProgCounter.vhd",
"CPU2.srcs\\sources_1\\computer\\debug.vhd",
"CPU2.srcs\\sources_1\\cpu\\MemoryAccess.vhd",
"CPU2.srcs\\sources_1\\cpu\\IoProcess.vhd",
"CPU2.srcs\\sources_1\\computer\\Computer.vhd",
"CPU2.srcs\\sources_1\\cpu\\Interrupt.vhd",
"CPU2.srcs\\sources_1\\cpu\\cpu_debug.vhd",
"CPU2.srcs\\sources_1\\cpu\\CPU.vhd",
"CPU2.srcs\\sources_1\\cpu\\ALU.vhd",
"CPU2.srcs\\sim_debugger\\new\\SimDebugger.vhd",
"CPU2.srcs\\sim_2\\computer\\SimUartDevice.vhd",
"CPU2.srcs\\sim_1\\computer\\SimCPU.vhd",
"CPU2.srcs\\sim_ioInterrupts\\new\\simIoInterrupts.vhd",
"CPU2.srcs\\sim_computer\\computer\\simComputer.vhd",
"CPU2.gen\\sources_1\\ip\\cpumemoryTEST\\cpumemoryTEST_sim_netlist.vhdl",
"CPU2.gen\\sources_1\\ip\\UIntMult\\hdl\\xbip_bram18k_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntMult\\hdl\\mult_gen_v12_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntMult\\sim\\UIntMult.vhd",
"CPU2.gen\\sources_1\\ip\\UIntMult\\UIntMult_stub.vhdl",
"CPU2.gen\\sources_1\\ip\\UIntMult\\synth\\UIntMult.vhd",
"CPU2.gen\\sources_1\\ip\\UIntMult\\UIntMult_sim_netlist.vhdl",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\UIntDiv_sim_netlist.vhdl",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\UIntDiv_stub.vhdl",
"CPU2.gen\\sources_1\\ip\\SIntMult\\synth\\SIntMult.vhd",
"CPU2.gen\\sources_1\\ip\\SIntMult\\SIntMult_stub.vhdl",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\div_gen_v5_1_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\axi_utils_v2_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\xbip_bram18k_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\mult_gen_v12_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\floating_point_v7_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\xbip_utils_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\xbip_pipe_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\xbip_dsp48_wrapper_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\xbip_dsp48_mult_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\xbip_dsp48_multadd_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\hdl\\xbip_dsp48_addsub_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntMult\\hdl\\xbip_utils_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntMult\\hdl\\xbip_pipe_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\cpumemoryTEST\\cpumemoryTEST_stub.vhdl",
"CPU2.gen\\sources_1\\ip\\SIntMult\\SIntMult_sim_netlist.vhdl",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\SIntDiv_stub.vhdl",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\SIntDiv_sim_netlist.vhdl",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\synth\\SIntDiv.vhd",
"CPU2.gen\\sources_1\\ip\\cpumemoryTEST\\misc\\blk_mem_gen_v8_4.vhd",
"CPU2.gen\\sources_1\\ip\\SerialDevice115k\\SerialDevice115k_stub.vhdl",
"CPU2.gen\\sources_1\\ip\\SerialDevice115k\\SerialDevice115k_sim_netlist.vhdl",
"CPU2.gen\\sources_1\\ip\\SerialDevice115k\\synth\\SerialDevice115k.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\demo_tb\\tb_SIntDiv.vhd",
"CPU2.gen\\sources_1\\ip\\SerialDevice115k\\hdl\\axi_uartlite_v2_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SerialDevice115k\\hdl\\axi_lite_ipif_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SerialDevice115k\\hdl\\lib_srl_fifo_v1_0_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SerialDevice115k\\hdl\\lib_pkg_v1_0_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SerialDevice115k\\hdl\\lib_cdc_v1_0_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntMult\\hdl\\xbip_utils_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntMult\\hdl\\xbip_pipe_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntMult\\hdl\\xbip_bram18k_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntMult\\hdl\\mult_gen_v12_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\cpumemory\\cpumemory_sim_netlist.vhdl",
"CPU2.gen\\sources_1\\ip\\cpumemoryTEST\\hdl\\blk_mem_gen_v8_4_vhsyn_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\cpumemory\\synth\\cpumemory.vhd",
"CPU2.gen\\sources_1\\ip\\cpumemory\\misc\\blk_mem_gen_v8_4.vhd",
"CPU2.gen\\sources_1\\ip\\cpumemory\\cpumemory_stub.vhdl",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\synth\\UIntDiv.vhd",
"CPU2.gen\\sources_1\\ip\\cpumemory\\hdl\\blk_mem_gen_v8_4_vhsyn_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntMult\\sim\\SIntMult.vhd",
"CPU2.gen\\sources_1\\ip\\cpumemoryTEST\\synth\\cpumemoryTEST.vhd",
"CPU2.gen\\sources_1\\ip\\SerialDevice115k\\sim\\SerialDevice115k.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\axi_utils_v2_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\xbip_dsp48_addsub_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\xbip_dsp48_multadd_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\xbip_bram18k_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\mult_gen_v12_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\floating_point_v7_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\div_gen_v5_1_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\xbip_dsp48_wrapper_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\xbip_utils_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\xbip_pipe_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\hdl\\xbip_dsp48_mult_v3_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\sim\\UIntDiv.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\axi_utils_v2_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\axi_uartlite_v2_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\axi_lite_ipif_v3_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\lib_srl_fifo_v1_0_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\mult_gen_v12_0_vh_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\SIntDiv\\sim\\SIntDiv.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\lib_pkg_v1_0_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\xbip_bram18k_v3_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\lib_cdc_v1_0_rfs.vhd",
"CPU2.gen\\sources_1\\ip\\UIntDiv\\demo_tb\\tb_UIntDiv.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\xbip_dsp48_mult_v3_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\xbip_dsp48_wrapper_v3_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\xbip_dsp48_multadd_v3_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\xbip_dsp48_addsub_v3_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\xbip_pipe_v3_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\floating_point_v7_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\xbip_utils_v3_0_vh_rfs.vhd",
"CPU2.ip_user_files\\ipstatic\\hdl\\div_gen_v5_1_vh_rfs.vhd",
"CPU2.ip_user_files\\ip\\SIntMult\\SIntMult_stub.vhdl",
]

UNISIM.files = [
  'C:\Xilinx\Vivado\2023.2\data\vhdl\src\unisims\unisim_VCOMP.vhd',
]
UNISIM.is_third_party = true
